---
- name: Source distribution-specific variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_facts.distribution | lower }}.yml'
      skip: true

- name: Ensure CRB repository is {{ 'enabled' if crb_repo_enabled else 'disabled' }}
  community.general.ini_file:
    path: '{{ crb_repo_file }}'
    section: crb
    option: enabled
    value: '{{ crb_repo_enabled | int }}'
    no_extra_spaces: true
    create: false
    modify_inactive_option: false
    owner: root
    group: root
    mode: '0644'
